#spring:
#  freemarker:
#    allow-request-override: false 
#    cache: true 
#    check-template-location: true 
#    charset: UTF-8 
#    content-type: text/html 
#    expose-request-attributes: true 
#    expose-session-attributes: false 
#    expose-spring-macro-helpers: false
#    # prefix:  
#    request-context-attribute: rc
#    #spring.freemarker.settings.*=
#    #模板加载后缀 
#    suffix: .html
#    #模板加载路径 
#    template-loader-path: classpath:/templates/ftl/

freemarker:
  templateLoaderPath: classpath:/templates/ftl/
  # freemarkerVariables:
  defaultEncoding: utf-8
  freemarkerSettings:
    template_update_delay: 0
    defaultEncoding: UTF-8
    url_escaping_charset: UTF-8
    locale: zh_CN
    boolean_format: true,false
    datetime_format: yyyy-MM-dd HH:mm:ss
    date_format: yyyy-MM-dd
    time_format: HH:mm:ss
    # number_format: 0.######
    number_format: #
    whitespace_stripping: true
    auto_import: /common/config/top.ftl as _top, /common/config/left.ftl as _left